data:
  data_dir: "imagenet_sketch"
  train_dir: "./data/train"
  train_info_file: "./data/train.csv"
  test_dir: "./data/test"
  test_info_file: "./data/test.csv"
  augmented_dir: "./data/augmented"
  augmented_info_file: "./data/augmented.csv"
model:
  name: "eff4"
  pretrained: True
  num_classes: 1000

training:
  mode : "train"
  batch_size: 32
  validation_ratio : 0.2
  num_epochs: 50
  additional_train: True
  additional_epochs: 5
  learning_rate: 0.001
  n_splits: 5
  device: "cuda"
  metric: "accuracy"

  criterion: "CrossEntropyLoss"
  optimizer:
    name: "Adam"
    weight_decay: 0.0001

  lr_scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 3
    min_lr: 1e-6
    monitor: 'metric'

  early_stopping:
    patience: 5
    min_delta: 0.001
    evidence: 'loss'
    monitor: 'metric'  

  augmentation:
    flip: 0.0
offline_augmentation:
  augmentation:
    flip: 1
    crop: 1
  ratio: 2


paths:
  save_dir: "./outputs/saved_models"
  log_dir: "./outputs/logs"
  output_dir: "./tests"

random_seed: 20010316